# AURION Windows MSI Builder - branded, upgrade-aware, per-user.
#
# Default: builds the branded WiX MSI (custom Update/Repair/Change-location
# wizard, AURION banner + icon, license/user-state preserved on upgrade).
#
# The WiX toolset 3.x is required. This script finds it in PATH or in
# "C:\Program Files (x86)\WiX Toolset v3*\bin" and, if missing, offers to
# download the official wix314.exe from github.com/wixtoolset/wix3 and
# install it silently.
#
# The .wxs is generated by build-msi.py (Python 3, no packages). Without
# Python the committed windows-app\packaging\aurion.wxs fallback is used.
#
#   powershell -ExecutionPolicy Bypass -File windows-app\packaging\build-msi.ps1
#   powershell -ExecutionPolicy Bypass -File windows-app\packaging\build-msi.ps1 -Electron
#
# -Electron: the OLD electron-builder MSI flow (stock wizard, no branding).
# -TreeOnly: skip the Electron app; ship the raw tree + script launcher
#            (console-based, not recommended for customers).
# Kept for reference; the branded WiX MSI above is the installer to ship.

param(
    [switch]$InstallDeps,
    [switch]$Electron,
    [switch]$TreeOnly
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$Dist = Join-Path $Root 'dist'

if ($Electron) {
    # ------------------------------------------------------------------
    # Legacy electron-builder flow (stock installer UI).
    # ------------------------------------------------------------------
    Write-Host "=== AURION MSI Builder (electron-builder, legacy) ===" -ForegroundColor Cyan
    $DesktopPkg = Join-Path $Root "windows-app\desktop\package.json"
    if (-not (Test-Path $DesktopPkg)) {
        Write-Error "windows-app/desktop/package.json not found"
    }
    Set-Location (Join-Path $Root "windows-app\desktop")
    if ($InstallDeps -or -not (Test-Path "node_modules\electron-builder")) {
        Write-Host "Installing dependencies..." -ForegroundColor Yellow
        npm install --no-audit --no-fund
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    }
    Write-Host "Building MSI installer (electron-builder)..." -ForegroundColor Cyan
    $env:USE_HARD_LINKS = "false"
    npx electron-builder --win msi --x64 --config.msi.perMachine=false --config.msi.oneClick=false --config.msi.createDesktopShortcut=always --config.msi.createStartMenuShortcut=true
    if ($LASTEXITCODE -eq 0) {
        Get-ChildItem (Join-Path $Root 'dist\desktop\*.msi') -ErrorAction SilentlyContinue |
            ForEach-Object { Write-Host "  MSI: $($_.FullName)" -ForegroundColor Green }
        Write-Host "Done." -ForegroundColor Green
    } else {
        Write-Error "MSI build failed"
    }
    exit $LASTEXITCODE
}

# ------------------------------------------------------------------
# Branded WiX build (the installer to ship).
# ------------------------------------------------------------------
Write-Host "=== AURION MSI Builder (branded WiX installer) ===" -ForegroundColor Cyan
Write-Host "Target: %LOCALAPPDATA%\Programs\AURION (per user, writable tree)" -ForegroundColor Green
Write-Host "Wizard: Update / Repair / Change location when an install is detected" -ForegroundColor Green
Write-Host ""

$WixDownloadUrl = "https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314.exe"

function Find-WixTool([string]$tool) {
    $cmd = Get-Command $tool -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    # WIX env var (set by the installer; visible in NEW terminals only)
    $wixEnv = [System.Environment]::GetEnvironmentVariable('WIX')
    if (-not $wixEnv) { $wixEnv = [System.Environment]::GetEnvironmentVariable('WIX', 'Machine') }
    if ($wixEnv) {
        $p = Join-Path $wixEnv "bin\$tool"
        if (Test-Path $p) { return $p }
    }
    # Registry InstallRoot written by the WiX 3.x installer (works in the SAME session)
    foreach ($rk in @('HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows Installer XML', 'HKLM:\SOFTWARE\Microsoft\Windows Installer XML')) {
        $vers = Get-ChildItem -Path $rk -ErrorAction SilentlyContinue
        foreach ($v in $vers) {
            $root = (Get-ItemProperty -Path $v.PSPath -ErrorAction SilentlyContinue).InstallRoot
            if ($root) {
                $p = Join-Path $root $tool
                if (Test-Path $p) { return $p }
            }
        }
    }
    $roots = @()
    if ($env:ProgramFiles) { $roots += $env:ProgramFiles }
    # NOTE: 'ProgramFiles(x86)' is a per-process variable (not in the Machine registry block)
    $pf86 = [System.Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
    if ($pf86) { $roots += $pf86 }
    $roots += 'C:\Program Files (x86)'
    $roots += 'C:\Program Files'
    $roots = $roots | Select-Object -Unique
    foreach ($r in $roots) {
        if (-not $r) { continue }
        $dirs = Get-ChildItem -Path $r -Filter 'WiX Toolset*' -Directory -ErrorAction SilentlyContinue
        foreach ($d in $dirs) {
            $p = Join-Path $d.FullName "bin\$tool"
            if (Test-Path $p) { return $p }
            $p2 = Join-Path $d.FullName $tool
            if (Test-Path $p2) { return $p2 }
        }
    }
    $choco = Join-Path $env:ChocolateyInstall "bin\$tool"
    if ($choco -and (Test-Path $choco)) { return $choco }
    return $null
}

function Install-WixToolset {
    Write-Host ""
    Write-Host "WiX toolset 3.x was not found." -ForegroundColor Yellow
    Write-Host "Official download: $WixDownloadUrl" -ForegroundColor Yellow
    $ans = Read-Host "Download and install WiX Toolset 3.14 now? [Y/n]"
    if ($ans -and $ans.Trim().ToLower() -notin @('y', 'yes', '')) {
        Write-Error "Install it first (or: choco install wixtoolset), then re-run this script."
    }
    $installer = Join-Path $env:TEMP "wix314-aurion.exe"
    Write-Host "Downloading..." -ForegroundColor Cyan
    try {
        Invoke-WebRequest -Uri $WixDownloadUrl -OutFile $installer -UseBasicParsing
    } catch {
        Write-Error "Download failed: $($_.Exception.Message). Open $WixDownloadUrl in a browser, run the installer, then re-run this script."
    }
    if ((Get-Item $installer).Length -lt 1MB) {
        Write-Error "Downloaded file is suspiciously small - check your connection and re-run."
    }
    Write-Host "Installing (silent)..." -ForegroundColor Cyan
    $p = Start-Process -FilePath $installer -ArgumentList "/q", "/norestart" -Wait -PassThru
    if ($p.ExitCode -ne 0) {
        Write-Error "WiX installer exited with code $($p.ExitCode). Note: on some Windows versions WiX 3 needs the '.NET Framework 3.5' Windows feature: Settings -> Apps -> Optional features -> Add a feature -> .NET Framework 3.5 (or: DISM /Online /Enable-Feature /FeatureName:NetFx3). Then re-run this script."
    }
    Remove-Item $installer -Force -ErrorAction SilentlyContinue
    Write-Host "WiX Toolset installed." -ForegroundColor Green
}

$Candle = Find-WixTool 'candle.exe'
$Light = Find-WixTool 'light.exe'
if (-not $Candle -or -not $Light) {
    Install-WixToolset
    $Candle = Find-WixTool 'candle.exe'
    $Light = Find-WixTool 'light.exe'
    if (-not $Candle -or -not $Light) {
        Write-Error "WiX toolset still not found after install. Check that 'C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe' exists; if it does not, the silent install failed (likely needs the .NET Framework 3.5 Windows feature: DISM /Online /Enable-Feature /FeatureName:NetFx3 /All), then re-run."
    }
}
Write-Host "candle: $Candle" -ForegroundColor Gray
Write-Host "light:  $Light" -ForegroundColor Gray
Write-Host ""

# 0) Build the Windows application (Electron, unpacked) that the MSI ships.
#    AURION.exe = native window; engine + desk run hidden inside it; on a
#    fresh machine it installs Python/Node/packages silently on first start.
$DesktopDir = Join-Path $Root 'windows-app\desktop'
$AppDir = Join-Path $Dist 'desktop\win-unpacked'
if (-not $TreeOnly) {
    $npmCmd = Get-Command npm -ErrorAction SilentlyContinue
    if (-not $npmCmd) {
        Write-Error "Node.js/npm not found - needed to build the AURION Windows app. Install Node.js 22 LTS (https://nodejs.org) and re-run (or pass -TreeOnly for the script-launcher MSI)."
    }
    Push-Location $DesktopDir
    if ($InstallDeps -or -not (Test-Path 'node_modules\electron-builder')) {
        Write-Host "Installing desktop build dependencies (electron, electron-builder)..." -ForegroundColor Yellow
        npm install --no-audit --no-fund
        if ($LASTEXITCODE -ne 0) { Pop-Location; Write-Error "npm install failed in windows-app\desktop" }
    }
    Write-Host "Building AURION.exe (electron-builder --dir)..." -ForegroundColor Cyan
    $env:USE_HARD_LINKS = 'false'
    $env:CSC_IDENTITY_AUTO_DISCOVERY = 'false'
    npx electron-builder --win --x64 --dir --config.forceCodeSigning=false
    $rc = $LASTEXITCODE
    Pop-Location
    if ($rc -ne 0) { Write-Error "electron-builder --dir failed" }
    if (-not (Test-Path (Join-Path $AppDir 'AURION.exe'))) { Write-Error "AURION.exe not found in $AppDir" }
    # electron-builder ran with signAndEditExecutable=false (no signtool/rcedit
    # needed), so stamp the AURION icon + version into AURION.exe ourselves.
    Write-Host "Branding AURION.exe (icon + version info)..." -ForegroundColor Cyan
    Push-Location $DesktopDir
    if (-not (Test-Path 'node_modules\resedit')) { npm install --no-audit --no-fund resedit@^2.0.3 }
    node brand-exe.js (Join-Path $AppDir 'AURION.exe') 'icon.ico'
    $rc = $LASTEXITCODE
    Pop-Location
    if ($rc -ne 0) { Write-Error "brand-exe.js failed (icon/version stamping)" }
    Write-Host "App: $AppDir" -ForegroundColor Green
}

# 1) Generate the .wxs with Python 3 (no packages required).
New-Item -ItemType Directory -Force -Path $Dist | Out-Null
$wxsFile = Join-Path $Dist 'aurion.wxs'
$py = $null
# The WindowsApps "python3.exe" is only a Store alias: Get-Command finds it,
# but running it does NOT run an interpreter -> the wxs would silently come
# from the stale committed fallback. Probe each candidate for a real CPython.
function Test-RealPython($path) {
    try {
        $out = & $path -c "import sys;print('.'.join(map(str,sys.version_info[:3])))" 2>$null
        return ($LASTEXITCODE -eq 0 -and ("$out" -match '^\d+\.\d+\.\d+$'))
    } catch { return $false }
}
foreach ($cand in @('python3', 'python', 'py')) {
    $cmd = Get-Command $cand -ErrorAction SilentlyContinue
    if ($cmd -and (Test-RealPython $cmd.Source)) { $py = $cmd.Source; break }
}
if ($py) {
    Write-Host "Generating aurion.wxs with $py ..." -ForegroundColor Yellow
    $genArgs = @('--wxs')
    if ($TreeOnly) { $genArgs += '--tree' } else { $genArgs += @('--app-dir', $AppDir) }
    & $py (Join-Path $PSScriptRoot 'build-msi.py') @genArgs
    if ($LASTEXITCODE -ne 0) { Write-Error "aurion.wxs generation failed" }
} else {
    if (-not $TreeOnly) { Write-Error "A real Python 3 is required to package the Electron app into the MSI, or pass -TreeOnly. If 'python3' exists but is the Microsoft Store alias: Settings > Apps > Advanced app settings > App execution aliases -> turn OFF python.exe/python3.exe, then install Python (winget install Python.Python.3.12)." }
    Write-Warning "Python 3 not found - using the committed fallback aurion.wxs (version number may be stale)."
    $fallback = Join-Path $PSScriptRoot 'aurion.wxs'
    if (-not (Test-Path $fallback)) {
        $fallback = $wxsFile
    }
    if (-not (Test-Path $fallback)) {
        Write-Error "No Python and no fallback aurion.wxs found. Install Python 3 (winget install Python.Python.3.12)."
    }
    Copy-Item $fallback $wxsFile -Force
    $assets = Join-Path (Split-Path $fallback -Parent) 'wix'
    if ((Split-Path $fallback -Parent) -ne $Dist -and (Test-Path $assets)) {
        Copy-Item $assets (Join-Path $Dist 'wix') -Recurse -Force
    }
    Write-Host "Using fallback: $fallback" -ForegroundColor Yellow
}

# 2) Compile: candle -> light.
Set-Location $Dist
$wixobj = Join-Path $Dist 'AURION.wixobj'
$msi = Join-Path $Dist 'AURION-Setup.msi'

Write-Host "candle ..." -ForegroundColor Cyan
& $Candle $wxsFile -arch x64 -ext WixUIExtension -ext WixUtilExtension -out $wixobj
if ($LASTEXITCODE -ne 0) { Write-Error "candle failed (see errors above)" }

Write-Host "light ..." -ForegroundColor Cyan
# -b: base dir for the relative WixVariable paths (wix\banner.bmp etc.)
# -sice:ICE61/ICE69/ICE38/ICE64: per-user LocalAppData layout noise
& $Light $wixobj -ext WixUIExtension -ext WixUtilExtension -cultures:en-us -b $PSScriptRoot -sice:ICE38 -sice:ICE64 -sice:ICE91 -spdb -out $msi
if ($LASTEXITCODE -ne 0) { Write-Error "light failed (see errors above)" }

Write-Host ""
Write-Host "MSI built successfully!" -ForegroundColor Green
$len = [math]::Round((Get-Item $msi).Length / 1MB, 2)
Write-Host "  MSI: $msi ($len MB)" -ForegroundColor White
Write-Host ""
Write-Host "Install behavior:" -ForegroundColor Cyan
Write-Host "  - Existing AURION detected -> Update / Repair / Change location dialog" -ForegroundColor Gray
Write-Host "  - Default path: %LOCALAPPDATA%\Programs\AURION (no admin needed)" -ForegroundColor Gray
Write-Host "  - License + user config + data are kept across updates" -ForegroundColor Gray
Write-Host "  - Desktop: AURION.lnk, Start Menu: AURION" -ForegroundColor Gray
