try {
  var sh = new ActiveXObject("WScript.Shell");
  var fso = new ActiveXObject("Scripting.FileSystemObject");
  var tmp = sh.ExpandEnvironmentStrings("%TEMP%");
  var file = tmp + "\\aurion-arp-clean.js";
  var own = (Session.Property("ProductCode") || "").toUpperCase();
  var mode = (Session.Property("AURION_REMOVING") == "1") ? "remove" : "clean";
  var keep = (Session.Property("AURION_KEEPDATA") == "1") ? 1 : 0;
  var unl = (Session.Property("REMOVE") == "ALL") ? 1 : 0;
  var dir = (Session.Property("INSTALLDIR") || "").replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
  var body = [

    'var OWN = "' + own + '";',
    'var MODE = "' + mode + '";',
    'var MYDIR = "' + dir + '";',
    'var KEEP = ' + keep + ';',
    'var CODES = "";',
    'var UNINSTALL = ' + unl + ';',
    'var ENGINE = 0;',
    'var POPUP = 0;',
    '// arp-clean-inner.js - the actual cleaner that runs detached (wscript).',
    '// build-msi.py wraps this file twice into JScript custom actions:',
    '//   wix/arp-clean.js      <- %TEMP%\\aurion-arp-clean.js     (after every transaction)',
    '//   wix/arp-remove-old.js <- %TEMP%\\aurion-arp-uninstall.js (wizard "Remove" button:',
    '//                            the setup is cancelled and the DETECTED install is',
    '//                            uninstalled from outside this MSI session)',
    '// Injected globals (written by the wrapper prolog, before this file):',
    '//   OWN  - this MSI\'s ProductCode            MODE  - clean | remove | uninstall-old',
    '//   MYDIR - install dir to wipe (may be "")  KEEP  - 1 = keep data/ + config/',
    '//   CODES - ";"-separated product codes to uninstall (uninstall-old only)',
    '//   UNINSTALL - 1 = this session is an uninstall (REMOVE=ALL)',
    '//   POPUP - 1 = standalone uninstaller: show start/done feedback popups',
    '//   ENGINE - 1 = standalone uninstaller: first try msiexec /x on OWN',
    '//   OWN = "SELF" -> discover the product code from the ARP entry that',
    '//          points to this script (installed uninstall-aurion.js)',
    '// Log: %TEMP%\\aurion-arp-clean.log',
    'var sh = new ActiveXObject("WScript.Shell"), fso = new ActiveXObject("Scripting.FileSystemObject");',
    'var tmp = sh.ExpandEnvironmentStrings("%TEMP%");',
    'var logf = fso.OpenTextFile(tmp + "\\\\aurion-arp-clean.log", 8, true);',
    'var admin = WScript.Arguments.Length > 0;',
    'var leftAdmin = false;',
    'function log(m) { try { logf.WriteLine(new Date().toLocaleTimeString() + " " + m); } catch (e) {} }',
    'function run(cmd) { try { return sh.Run(cmd, 0, true); } catch (e) { return -1; } }',
    'function squish(g) {',
    '  var p = g.replace(/[{}]/g, "").split("-"); var r = function (s) { return s.split("").reverse().join(""); };',
    '  var sw = function (s) { var o = ""; for (var i = 0; i < s.length; i += 2) o += s.charAt(i + 1) + s.charAt(i); return o; };',
    '  return (r(p[0]) + r(p[1]) + r(p[2]) + sw(p[3]) + sw(p[4])).toUpperCase();',
    '}',
    'var reg = null;',
    'function val(h, k, n) { if (!reg) return ""; var o = {}; try { var m = reg.Methods_.Item("GetStringValue").InParameters.SpawnInstance_(); m.hDefKey = h; m.sSubKeyName = k; m.sValueName = n; var out = reg.ExecMethod_("GetStringValue", m); return out.ReturnValue === 0 ? String(out.sValue) : ""; } catch (e) { return ""; } }',
    'function keys(h, k) { if (!reg) return []; try { var m = reg.Methods_.Item("EnumKey").InParameters.SpawnInstance_(); m.hDefKey = h; m.sSubKeyName = k; var out = reg.ExecMethod_("EnumKey", m); var a = []; if (out.ReturnValue === 0 && out.sNames !== null) { var v = new VBArray(out.sNames).toArray(); for (var i = 0; i < v.length; i++) a.push(String(v[i])); } return a; } catch (e) { return []; } }',
    'function exists(h, k) { return keys(h, k).length > 0 || val(h, k, "DisplayName") !== ""; }',
    'try { reg = GetObject("winmgmts:{impersonationLevel=impersonate}!\\\\\\\\.\\\\root\\\\default:StdRegProv"); }',
    'catch (eR) { log("wmi unavailable: " + (eR.message || eR)); }',
    'log("start mode=" + MODE + " own=" + OWN + (admin ? " (elevated)" : ""));',
    'var HIVES = [[0x80000001, "HKCU"], [0x80000002, "HKLM"]];',
    'var PATHS = ["SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Uninstall", "SOFTWARE\\\\WOW6432Node\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Uninstall"];',
    '// ---- 0) SELF discovery: the installed uninstall-aurion.js does not know its',
    '// product code at packaging time (Product Id="*"). It is found by locating',
    '// the ARP entry whose UninstallString contains this very script\'s path.',
    'if (OWN === "SELF") {',
    '  for (var hs = 0; hs < HIVES.length && OWN === "SELF"; hs++) {',
    '    for (var ps = 0; ps < PATHS.length && OWN === "SELF"; ps++) {',
    '      var sn = keys(HIVES[hs][0], PATHS[ps]);',
    '      for (var si = 0; si < sn.length; si++) {',
    '        var sk = PATHS[ps] + "\\\\" + sn[si];',
    '        var sdn = val(HIVES[hs][0], sk, "DisplayName");',
    '        if (!/^AURION(\\s|$)/i.test(sdn)) continue;',
    '        var sus = val(HIVES[hs][0], sk, "UninstallString");',
    '        if (!/^\\{[0-9A-F-]{36}\\}$/i.test(sn[si])) continue;',
    '        if (sus.toLowerCase().indexOf(WScript.ScriptFullName.toLowerCase()) < 0) continue;',
    '        OWN = sn[si].toUpperCase();',
    '        var sil = val(HIVES[hs][0], sk, "InstallLocation");',
    '        if (sil) MYDIR = sil;',
    '        log("found self product " + OWN + " under " + HIVES[hs][1] + "\\\\" + sk);',
    '        break;',
    '      }',
    '    }',
    '  }',
    '  if (OWN === "SELF") { OWN = "{00000000-0000-0000-0000-000000000000}"; log("self product code not found - cleaning files only"); }',
    '}',
    '// moved-install fallback: when nothing told us where the app lives, trust',
    '// the folder this script itself lives in - but only if it really looks like',
    '// an AURION tree (guards against running a copied script somewhere random).',
    'if ((MODE === "remove" || MODE === "uninstall-old") && !MYDIR) {',
    '  var sdir = String(WScript.ScriptFullName).replace(/\\\\[^\\\\]+$/, "");',
    '  if (fso.FileExists(sdir + "\\\\AURION.exe") || fso.FolderExists(sdir + "\\\\resources")) {',
    '    MYDIR = sdir;',
    '    log("using script folder as install dir: " + sdir);',
    '  }',
    '}',
    'if (POPUP === 1 && !admin) {',
    '  try { sh.Popup("AURION is being removed from this computer. Your license and data stay for future installs.", 4, "AURION Uninstaller", 64); } catch (eP0) {}',
    '}',
    'if (MODE === "remove" || MODE === "uninstall-old") { run("taskkill.exe /F /T /IM AURION.exe"); }',
    '// ---- 1) stale sweep: every OTHER "AURION" entry in Apps & features --------',
    'for (var hi = 0; hi < HIVES.length; hi++) {',
    '  for (var pi = 0; pi < PATHS.length; pi++) {',
    '    var hive = HIVES[hi][0], hname = HIVES[hi][1], base = PATHS[pi];',
    '    var names = keys(hive, base);',
    '    for (var i = 0; i < names.length; i++) {',
    '      var name = names[i], key = base + "\\\\" + name;',
    '      var dn = val(hive, key, "DisplayName");',
    '      if (!/^AURION(\\s|$)/i.test(dn)) continue;',
    '      if (name.toUpperCase() === OWN) continue;',
    '      log("stale entry " + hname + "\\\\" + key + " (" + dn + ")");',
    '      var isMsi = /^\\{[0-9A-F-]{36}\\}$/i.test(name);',
    '      if (isMsi) {',
    '        var rc = 1618, tries = 0;',
    '        while (rc === 1618 && tries++ < 60) { rc = run("msiexec.exe /x " + name + " /qn /norestart"); if (rc === 1618) WScript.Sleep(3000); }',
    '        log("msiexec /x " + name + " -> " + rc);',
    '      }',
    '      if (exists(hive, key)) {',
    '        if (hname !== "HKCU" && !admin) { log("still present under " + hname + " - needs admin, will retry elevated"); leftAdmin = true; continue; }',
    '        run("reg.exe delete \\"" + hname + "\\\\" + key + "\\" /f");',
    '        if (isMsi && hname === "HKCU") {',
    '          var sq = squish(name);',
    '          run("reg.exe delete \\"HKCU\\\\Software\\\\Microsoft\\\\Installer\\\\Products\\\\" + sq + "\\" /f");',
    '          run("reg.exe delete \\"HKCU\\\\Software\\\\Microsoft\\\\Installer\\\\Features\\\\" + sq + "\\" /f");',
    '        }',
    '        log("force-removed registration " + name);',
    '      }',
    '    }',
    '  }',
    '}',
    '// ---- 2) uninstall-old: silently uninstall the DETECTED previous products ---',
    'if (MODE === "uninstall-old") {',
    '  var codes = String(CODES || "").split(";");',
    '  var seenC = ",";',
    '  for (var ci = 0; ci < codes.length; ci++) {',
    '    var code = String(codes[ci]).replace(/^\\s+|\\s+$/g, "").toUpperCase();',
    '    if (!/^\\{[0-9A-F-]{36}\\}$/i.test(code) || seenC.indexOf("," + code + ",") >= 0) continue;',
    '    seenC += code + ",";',
    '    var regd = false;',
    '    for (var hq = 0; hq < HIVES.length && !regd; hq++) { for (var pq = 0; pq < PATHS.length && !regd; pq++) { if (exists(HIVES[hq][0], PATHS[pq] + "\\\\" + code)) regd = true; } }',
    '    if (!regd) { log("code not registered, skipping " + code); continue; }',
    '    log("uninstalling previous product " + code);',
    '    var rc2 = 1618, t2 = 0;',
    '    while (rc2 === 1618 && t2++ < 60) { rc2 = run("msiexec.exe /x " + code + " /passive /norestart"); if (rc2 === 1618) WScript.Sleep(3000); }',
    '    log("msiexec /x " + code + " -> " + rc2);',
    '    for (var hi3 = 0; hi3 < HIVES.length; hi3++) {',
    '      for (var pi3 = 0; pi3 < PATHS.length; pi3++) {',
    '        var ck = PATHS[pi3] + "\\\\" + code;',
    '        if (!exists(HIVES[hi3][0], ck)) continue;',
    '        if (HIVES[hi3][1] !== "HKCU" && !admin) { log("leftover under " + HIVES[hi3][1] + " - needs admin, will retry elevated"); leftAdmin = true; continue; }',
    '        run("reg.exe delete \\"" + HIVES[hi3][1] + "\\\\" + ck + "\\" /f");',
    '      }',
    '    }',
    '    var csq = squish(code);',
    '    run("reg.exe delete \\"HKCU\\\\Software\\\\Microsoft\\\\Installer\\\\Products\\\\" + csq + "\\" /f");',
    '    run("reg.exe delete \\"HKCU\\\\Software\\\\Microsoft\\\\Installer\\\\Features\\\\" + csq + "\\" /f");',
    '    log("cleaned registration " + code);',
    '  }',
    '}',
    '// ---- 3) full removal of the program tree (remove / uninstall-old) ---------',
    '// data/ + config/ are copied to %TEMP% first and restored after, so the',
    '// license survives no matter how deep it sits (resources\\data in the',
    '// Electron layout, data in the script-tree layout).',
    'if (MODE === "remove" || MODE === "uninstall-old") {',
    '  // standalone uninstaller (ENGINE=1): give the MSI engine the first,',
    '  // best chance to remove its own registration (shows a real progress',
    '  // bar). Inside a wizard session (ENGINE=0) the engine is already busy.',
    '  if (MODE === "remove" && ENGINE === 1 && OWN.charAt(1) !== "0") {',
    '    log("engine uninstall " + OWN);',
    '    var rcE = run("msiexec.exe /x " + OWN + " /passive /norestart");',
    '    log("msiexec /x own -> " + rcE);',
    '  }',
    '  var cands = [];',
    '  if (MYDIR) cands.push(MYDIR);',
    '  var ip = val(0x80000001, "Software\\\\AURION", "InstallPath");',
    '  if (ip) cands.push(ip);',
    '  cands.push(sh.ExpandEnvironmentStrings("%LOCALAPPDATA%") + "\\\\Programs\\\\AURION");',
    '  var uniq = [], seen = ",";',
    '  for (var c = 0; c < cands.length; c++) {',
    '    var rd = String(cands[c]).replace(/[\\\\\\/]+$/, "");',
    '    if (rd && seen.indexOf("," + rd.toLowerCase() + ",") < 0) { seen += rd.toLowerCase() + ","; uniq.push(rd); }',
    '  }',
    '  var keepFrom = null, cfgFrom = null, restoreIn = null;',
    '  if (KEEP) {',
    '    for (var kc = 0; kc < uniq.length && !keepFrom; kc++) {',
    '      var r = uniq[kc];',
    '      var res = r + "\\\\resources";',
    '      var base2 = fso.FolderExists(res) ? res : r;',
    '      if (fso.FolderExists(base2 + "\\\\data")) { keepFrom = base2 + "\\\\data"; restoreIn = base2; }',
    '      if (fso.FolderExists(base2 + "\\\\config")) cfgFrom = base2 + "\\\\config";',
    '      else if (fso.FolderExists(r + "\\\\config")) cfgFrom = r + "\\\\config";',
    '    }',
    '  }',
    '  var keepDir = tmp + "\\\\aurion-keep";',
    '  var haveKeep = false;',
    '  if (keepFrom || cfgFrom) {',
    '    try {',
    '      if (fso.FolderExists(keepDir)) fso.DeleteFolder(keepDir, true);',
    '      fso.CreateFolder(keepDir);',
    '      if (keepFrom) fso.CopyFolder(keepFrom, keepDir + "\\\\data");',
    '      if (cfgFrom) fso.CopyFolder(cfgFrom, keepDir + "\\\\config");',
    '      haveKeep = true;',
    '      log("keeping " + keepFrom + (cfgFrom ? " + " + cfgFrom : ""));',
    '    } catch (eK) { log("keep-copy failed: " + (eK.message || eK)); }',
    '  }',
    '  for (var c2 = 0; c2 < uniq.length; c2++) {',
    '    if (!fso.FolderExists(uniq[c2])) continue;',
    '    try { fso.DeleteFolder(uniq[c2], true); log("removed " + uniq[c2]); } catch (eD) { log("remove failed " + uniq[c2] + ": " + (eD.message || eD)); }',
    '  }',
    '  if (haveKeep && restoreIn) {',
    '    try {',
    '      var parts = restoreIn.split("\\\\");',
    '      var acc = "";',
    '      for (var pp = 0; pp < parts.length; pp++) { acc = acc ? acc + "\\\\" + parts[pp] : parts[pp]; if (!fso.FolderExists(acc)) fso.CreateFolder(acc); }',
    '      if (fso.FolderExists(keepDir + "\\\\data")) fso.CopyFolder(keepDir + "\\\\data", restoreIn + "\\\\data");',
    '      if (fso.FolderExists(keepDir + "\\\\config")) fso.CopyFolder(keepDir + "\\\\config", restoreIn + "\\\\config");',
    '      fso.DeleteFolder(keepDir, true);',
    '      log("restored data/config in " + restoreIn);',
    '    } catch (eR2) { log("restore failed: " + (eR2.message || eR2)); }',
    '  }',
    '  run("reg.exe delete \\"HKCU\\\\Software\\\\AURION\\" /f");',
    '  for (var hi2 = 0; hi2 < HIVES.length; hi2++) {',
    '    for (var pi2 = 0; pi2 < PATHS.length; pi2++) {',
    '      var ownKey = PATHS[pi2] + "\\\\" + OWN;',
    '      if (!exists(HIVES[hi2][0], ownKey)) continue;',
    '      if (HIVES[hi2][1] !== "HKCU" && !admin) { log("own entry under " + HIVES[hi2][1] + " needs admin, will retry elevated"); leftAdmin = true; continue; }',
    '      run("reg.exe delete \\"" + HIVES[hi2][1] + "\\\\" + ownKey + "\\" /f");',
    '      if (HIVES[hi2][1] === "HKCU") {',
    '        var osq = squish(OWN);',
    '        run("reg.exe delete \\"HKCU\\\\Software\\\\Microsoft\\\\Installer\\\\Products\\\\" + osq + "\\" /f");',
    '        run("reg.exe delete \\"HKCU\\\\Software\\\\Microsoft\\\\Installer\\\\Features\\\\" + osq + "\\" /f");',
    '      }',
    '      log("removed own registration " + OWN);',
    '    }',
    '  }',
    '  // every shortcut the installer may have created (+ taskbar/start pinned)',
    '  var lnks = [',
    '    sh.SpecialFolders("Desktop") + "\\\\AURION.lnk",',
    '    sh.ExpandEnvironmentStrings("%APPDATA%") + "\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\AURION.lnk",',
    '    sh.ExpandEnvironmentStrings("%APPDATA%") + "\\\\Microsoft\\\\Internet Explorer\\\\Quick Launch\\\\User Pinned\\\\TaskBar\\\\AURION.lnk",',
    '    sh.ExpandEnvironmentStrings("%APPDATA%") + "\\\\Microsoft\\\\Internet Explorer\\\\Quick Launch\\\\User Pinned\\\\StartMenu\\\\AURION.lnk"',
    '  ];',
    '  for (var li = 0; li < lnks.length; li++) { try { if (fso.FileExists(lnks[li])) { fso.DeleteFile(lnks[li], false); log("removed shortcut " + lnks[li]); } } catch (eA) {} }',
    '  var sm = sh.ExpandEnvironmentStrings("%APPDATA%") + "\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\AURION";',
    '  try { if (fso.FolderExists(sm)) { fso.DeleteFolder(sm, true); log("removed start menu folder " + sm); } } catch (e9) {}',
    '}',
    '// ---- 4) uninstall transactions: also drop the runtime-written node_modules',
    'if (UNINSTALL === 1) {',
    '  var nmDirs = [];',
    '  if (MYDIR) nmDirs.push(MYDIR);',
    '  var ipu = val(0x80000001, "Software\\\\AURION", "InstallPath");',
    '  if (ipu) nmDirs.push(ipu);',
    '  nmDirs.push(sh.ExpandEnvironmentStrings("%LOCALAPPDATA%") + "\\\\Programs\\\\AURION");',
    '  for (var c3 = 0; c3 < nmDirs.length; c3++) {',
    '    var nm = String(nmDirs[c3]).replace(/[\\\\\\/]+$/, "") + "\\\\backend\\\\node_modules";',
    '    if (fso.FolderExists(nm)) { try { fso.DeleteFolder(nm, true); log("removed runtime node_modules: " + nm); } catch (eN) {} }',
    '  }',
    '}',
    '// ---- 5) one guarded elevated retry for HKLM leftovers ----------------------',
    'if (leftAdmin && !admin) {',
    '  var flag = tmp + "\\\\aurion-arp-clean-admin.flag";',
    '  if (fso.FileExists(flag)) { log("elevated retry already attempted once - HKLM entries left in place"); }',
    '  else {',
    '    try { fso.CreateTextFile(flag, true).Close(); } catch (e2) {}',
    '    try {',
    '      var shApp = new ActiveXObject("Shell.Application");',
    '      shApp.ShellExecute("wscript.exe", "\\"" + WScript.ScriptFullName + "\\" /admin", "", "runas", 1);',
    '      log("elevated retry launched (accept the UAC prompt)");',
    '    } catch (e3) { log("elevated retry failed/declined: " + (e3.message || e3)); }',
    '  }',
    '}',
    'if (admin) { try { fso.DeleteFile(tmp + "\\\\aurion-arp-clean-admin.flag", false); } catch (e4) {} }',
    'if (POPUP === 1 && !admin && (MODE === "remove" || MODE === "uninstall-old")) {',
    '  try { sh.Popup("AURION has been removed from this computer.", 5, "AURION Uninstaller", 64); } catch (eP1) {}',
    '}',
    'log("done"); logf.Close();',
  ].join("\r\n");
  var f = fso.CreateTextFile(file, true); f.Write(body); f.Close();
  sh.Run("wscript.exe //B //Nologo \"" + file + "\"", 0, false);
} catch (e) {}