from __future__ import annotations

from copy import deepcopy
from typing import Any

# Built-in IDs are factory-sealed. Only "custom" may be edited from the desk.
LOCKED_IDS = frozenset({"conservative", "ftmo_challenge", "fundingpips", "the5ers"})

PROFILES: dict[str, dict[str, Any]] = {
    "conservative": {
        "id": "conservative",
        "locked": True,
        "label": {"en": "Conservative desk", "fa": "میز محافظه‌کار", "ar": "مكتب محافظ"},
        "about": {
            "en": "Tight in-house book. Small size, few tickets, no news window.",
            "fa": "دفتر داخلی تنگ. حجم کم، تعداد کم، بدون پنجرهٔ خبر.",
            "ar": "دفتر داخلي ضيّق. حجم صغير وعدد قليل دون نافذة أخبار.",
        },
        "max_daily_loss_pct": 2.0,
        "max_drawdown_pct": 5.0,
        "max_daily_profit_pct": 3.0,
        "profit_target_pct": 6.0,
        "max_lot": 0.30,
        "max_lot_per_symbol": 0.30,
        "max_open_trades": 2,
        "max_positions_per_symbol": 1,
        "max_trades_per_day": 6,
        "max_risk_per_trade_pct": 0.40,
        "max_consecutive_losses": 3,
        "min_minutes_between_trades": 15,
        "min_hold_minutes": 5,
        "max_hold_hours": 12,
        "trading_hours": {"start": "07:00", "end": "20:00", "weekdays": [0, 1, 2, 3, 4]},
        "news_filter": False,
        "news_blackout_before": 0,
        "news_blackout_after": 0,
        "allow_weekend": False,
        "allow_hold_over_weekend": False,
        "friday_close_utc_hour": 20,
        "hedging_allowed": False,
        "on_violation": "flatten_and_lock",
        "allowed_symbols": "",
        "consistency_max_trade_pct": 0.0,
    },
    "ftmo_challenge": {
        "id": "ftmo_challenge",
        "locked": True,
        "label": {"en": "FTMO-style challenge", "fa": "چالش به سبک FTMO", "ar": "تحدّي بأسلوب FTMO"},
        "about": {
            "en": "5% daily / 10% max DD, 10% target, news blackout, no weekend hold.",
            "fa": "۵٪ روزانه / ۱۰٪ دراودان، هدف ۱۰٪، فیلتر خبر، بدون نگه‌داشتن آخر هفته.",
            "ar": "٥٪ يومي / ١٠٪ تراجع، هدف ١٠٪، حظر أخبار، بلا احتفاظ عطلة.",
        },
        "max_daily_loss_pct": 5.0,
        "max_drawdown_pct": 10.0,
        "max_daily_profit_pct": 0.0,
        "profit_target_pct": 10.0,
        "max_lot": 2.00,
        "max_lot_per_symbol": 2.00,
        "max_open_trades": 5,
        "max_positions_per_symbol": 2,
        "max_trades_per_day": 0,
        "max_risk_per_trade_pct": 1.00,
        "max_consecutive_losses": 0,
        "min_minutes_between_trades": 0,
        "min_hold_minutes": 0,
        "max_hold_hours": 0,
        "trading_hours": {"start": "00:05", "end": "23:50", "weekdays": [0, 1, 2, 3, 4]},
        "news_filter": True,
        "news_blackout_before": 15,
        "news_blackout_after": 15,
        "allow_weekend": False,
        "allow_hold_over_weekend": False,
        "friday_close_utc_hour": 21,
        "hedging_allowed": True,
        "on_violation": "flatten_and_lock",
        "allowed_symbols": "",
        "consistency_max_trade_pct": 0.0,
    },
    "fundingpips": {
        "id": "fundingpips",
        "locked": True,
        "label": {"en": "FundingPips-style", "fa": "سبک فاندینگ‌پیپس", "ar": "أسلوب FundingPips"},
        "about": {
            "en": "4% daily / 6% max DD, 8% target, no hedge, 10-minute gap, news on.",
            "fa": "۴٪ روزانه / ۶٪ دراودان، هدف ۸٪، بدون هج، فاصله ۱۰ دقیقه، خبر روشن.",
            "ar": "٤٪ يومي / ٦٪ تراجع، هدف ٨٪، بلا تحوّط، فاصل ١٠ دقائق، أخبار مفعّلة.",
        },
        "max_daily_loss_pct": 4.0,
        "max_drawdown_pct": 6.0,
        "max_daily_profit_pct": 0.0,
        "profit_target_pct": 8.0,
        "max_lot": 1.00,
        "max_lot_per_symbol": 0.80,
        "max_open_trades": 3,
        "max_positions_per_symbol": 1,
        "max_trades_per_day": 8,
        "max_risk_per_trade_pct": 0.75,
        "max_consecutive_losses": 4,
        "min_minutes_between_trades": 10,
        "min_hold_minutes": 2,
        "max_hold_hours": 24,
        "trading_hours": {"start": "01:00", "end": "21:00", "weekdays": [0, 1, 2, 3, 4]},
        "news_filter": True,
        "news_blackout_before": 10,
        "news_blackout_after": 10,
        "allow_weekend": False,
        "allow_hold_over_weekend": False,
        "friday_close_utc_hour": 20,
        "hedging_allowed": False,
        "on_violation": "flatten_and_lock",
        "allowed_symbols": "",
        "consistency_max_trade_pct": 0.0,
    },
    "the5ers": {
        "id": "the5ers",
        "locked": True,
        "label": {"en": "The5ers-style", "fa": "سبک The5ers", "ar": "أسلوب The5ers"},
        "about": {
            "en": "5% daily / 6% max DD, 8% target, more tickets, overnight hold allowed.",
            "fa": "۵٪ روزانه / ۶٪ دراودان، هدف ۸٪، معاملات بیشتر، نگه‌داشتن شبانه مجاز.",
            "ar": "٥٪ يومي / ٦٪ تراجع، هدف ٨٪، صفقات أكثر، احتفاظ ليلي مسموح.",
        },
        "max_daily_loss_pct": 5.0,
        "max_drawdown_pct": 6.0,
        "max_daily_profit_pct": 0.0,
        "profit_target_pct": 8.0,
        "max_lot": 2.50,
        "max_lot_per_symbol": 1.50,
        "max_open_trades": 8,
        "max_positions_per_symbol": 2,
        "max_trades_per_day": 20,
        "max_risk_per_trade_pct": 1.25,
        "max_consecutive_losses": 0,
        "min_minutes_between_trades": 0,
        "min_hold_minutes": 0,
        "max_hold_hours": 72,
        "trading_hours": {"start": "00:10", "end": "23:50", "weekdays": [0, 1, 2, 3, 4]},
        "news_filter": False,
        "news_blackout_before": 0,
        "news_blackout_after": 0,
        "allow_weekend": False,
        "allow_hold_over_weekend": True,
        "friday_close_utc_hour": 22,
        "hedging_allowed": True,
        "on_violation": "lock",
        "allowed_symbols": "",
        "consistency_max_trade_pct": 0.0,
    },
    "custom": {
        "id": "custom",
        "locked": False,
        "label": {"en": "Custom", "fa": "سفارشی", "ar": "مخصّص"},
        "about": {
            "en": "Your book. Every field is editable and saved on this engine.",
            "fa": "دفتر خودتان. همه فیلدها قابل ویرایش‌اند و روی همین موتور ذخیره می‌شوند.",
            "ar": "دفترك. كل الحقول قابلة للتحرير وتُحفظ على هذا المحرك.",
        },
        "max_daily_loss_pct": 3.0,
        "max_drawdown_pct": 6.0,
        "max_daily_profit_pct": 0.0,
        "profit_target_pct": 0.0,
        "max_lot": 1.00,
        "max_lot_per_symbol": 0.0,
        "max_open_trades": 3,
        "max_positions_per_symbol": 1,
        "max_trades_per_day": 0,
        "max_risk_per_trade_pct": 0.75,
        "max_consecutive_losses": 0,
        "min_minutes_between_trades": 0,
        "min_hold_minutes": 0,
        "max_hold_hours": 0,
        "trading_hours": {"start": "00:15", "end": "23:45", "weekdays": [0, 1, 2, 3, 4]},
        "news_filter": False,
        "news_blackout_before": 15,
        "news_blackout_after": 15,
        "allow_weekend": False,
        "allow_hold_over_weekend": False,
        "friday_close_utc_hour": 21,
        "hedging_allowed": True,
        "on_violation": "lock",
        "allowed_symbols": "",
        "consistency_max_trade_pct": 0.0,
    },
}


EXTRAS: dict[str, Any] = {
    "min_hold_minutes": 0.0,
    "max_hold_hours": 0.0,
    "max_trades_per_day": 0,
    "hedging_allowed": True,
    "max_lot_per_symbol": 0.0,
    "profit_target_pct": 0.0,
    "news_blackout_before": 15,
    "news_blackout_after": 15,
    "consistency_max_trade_pct": 0.0,
    "max_daily_profit_pct": 0.0,
    "friday_close_utc_hour": 21,
    "max_consecutive_losses": 0,
    "min_minutes_between_trades": 0,
    "allowed_symbols": "",
    "locked": False,
    "about": {},
}


def get_profile(name: str) -> dict[str, Any]:
    key = str(name or "conservative")
    profile = deepcopy(PROFILES.get(key) or PROFILES["conservative"])
    for extra_key, value in EXTRAS.items():
        profile.setdefault(extra_key, value)
    profile["locked"] = profile.get("id") in LOCKED_IDS
    return profile
